spring:
  datasource:
    url: jdbc:postgresql://localhost:15432/airline
    username: postgres
    password: root
  jpa:
    generate-ddl: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: airline-service
server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: "*"