spring:
  datasource:
    url: jdbc:postgresql://localhost:15432/airline
    username: postgres
    password: root
  profiles:
    active: prod
  jpa:
    generate-ddl: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: airline-service
server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: "*"
jwt:
  secret: java_web_token_key
  expirationMin: 10

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}