logging:
  file:
    name: logs/application-debug.log
    max-size: 10MB
  pattern:
    file: "%d{dd-MM-yyyy HH:mm:ss.SSS} [%thread] %-5level %logger{36}.%M - %msg%n"
    rolling-file-name: logs/archived/application-debug-%d{yyyy-MM-dd}.%i.log
  level:
    root: info
    com.godeltech: warn
    org.hibernate: warn